const defaultStyles = {
  body: {
    color: 'text',
    backgroundColor: 'background',
    padding: 5,
    fontFamily: 'body',
    lineHeight: 'body',
    fontWeight: 'body',
    minHeight: '100%',
  },
  h1: {
    color: 'text',
    fontFamily: 'heading',
    lineHeight: 'heading',
    fontWeight: 'heading',
    fontSize: 5,
  },
  h2: {
    color: 'text',
    fontFamily: 'heading',
    lineHeight: 'heading',
    fontWeight: 'heading',
    fontSize: 4,
  },
  h3: {
    color: 'text',
    fontFamily: 'heading',
    lineHeight: 'heading',
    fontWeight: 'heading',
    fontSize: 3,
  },
  h4: {
    color: 'text',
    fontFamily: 'heading',
    lineHeight: 'heading',
    fontWeight: 'heading',
    fontSize: 2,
  },
  h5: {
    color: 'text',
    fontFamily: 'heading',
    lineHeight: 'heading',
    fontWeight: 'heading',
    fontSize: 1,
  },
  h6: {
    color: 'text',
    fontFamily: 'heading',
    lineHeight: 'heading',
    fontWeight: 'heading',
    fontSize: 0,
  },
  p: {
    color: 'text',
    fontFamily: 'body',
    fontWeight: 'body',
    lineHeight: 'body',
    fontSize: 1,
  },
  a: {
    color: 'link',
  },
  pre: {
    fontFamily: 'monospace',
    overflowX: 'auto',
    code: {
      color: 'inherit',
    },
  },
  code: {
    fontFamily: 'monospace',
    fontSize: 'inherit',
  },
  table: {
    width: '100%',
    borderCollapse: 'separate',
    borderSpacing: 0,
  },
  th: {
    textAlign: 'left',
    borderBottomStyle: 'solid',
  },
  td: {
    textAlign: 'left',
    borderBottomStyle: 'solid',
  },
  img: {
    maxWidth: '100%',
  },
  input: {
    color: 'text',
    backgroundColor: 'muted',
    padding: '5px',
    width: '100%',
    fontSize: 3,
  },
  select: {
    color: 'text',
    background: 'muted',
    border: 'none',
    fontSize: 3,
  },
  options: {
    color: 'text',
    background: 'muted',
    width: '100%',
    border: 'none',
    overflowX: 'hidden',
    fontSize: 3,
  },
  option: {
    color: 'text',
    background: 'muted',
    cursor: 'pointer',
    width: '100%',
    overflowX: 'hidden',
    fontSize: 3,
  },
  multiSelect: {
    fontSize: 3,
  },
  multiOption: {
    color: 'text',
    background: 'muted',
    overflowX: 'hidden',
    fontSize: 3,
  },
  multiOptions: {
    fontSize: 3,
  },
  multiSelectList: {},
  checkbox: {
    color: 'text',
    background: 'muted',
  },
  list: {
    color: 'text',
    background: 'muted',
    overflowX: 'hidden',
    overflowY: 'auto',
  },
  header: {
    backgroundColor: 'background',
    padding: '5px 30px',
    width: '100%',
    position: 'fixed',
    top: 0,
    left: 0,
    zIndex: 1000,
    height: '5rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  home: {
    color: 'secondary',
    fontSize: '2rem',
    fontWeight: 700,
    textDecoration: 'none',
  },
  theme: {
    width: '12rem',
    marginTop: '5px',
    marginRight: '3.5rem',
    fontSize: 2,
  },
  races: {
    fontSize: 4,
  },
  text: {
    color: 'text',
    fontSize: 3,
  },
  box: {
    color: 'text',
  },
  form: {
    color: 'text',
    border: '1px solid',
    borderColor: 'muted',
    borderRadius: '4px',
    padding: '1.5rem',
    marginTop: 3,
    marginBottom: 3,
    display: 'flex',
    flexDirection: 'column',
  },
  formControls: {
    fontSize: 3,
    margin: 'auto 0 1rem 0',
  },
  chip: {
    color: 'sharp',
    fontSize: 3,
    padding: '2rem 1rem 2rem 0.8rem',
  },
  card: {
    color: 'sharp',
    backgroundColor: 'card',
    fontSize: 3,
  },
  controlButton: {
    fontSize: 3,
    width: '8rem',
    height: '4rem',
  },
  linkButton: {
    fontSize: 2,
    color: 'linkButton',
    borderColor: 'linkButton',
    padding: '1rem',
  },
  error: {
    background: 'errorbg',
    color: 'red',
  },
  colors: {
    race: 'red',
    advantage: 'orange',
    equipment: '#08cc00',
  },
}

export default defaultStyles
